### ISSUE TITLE
Critical bug.

### ISSUE THREAD

**Issue by internetdesu** [Ivasik78/GlibysVoiceChat#10]
Server 1.12.2, on MAGMA (Magma is based on Forge and Paper, meaning it can run both Craftbukkit/Spigot/Paper plugins and Forge mods)
Plugins: greentext, simplesit, sethome
mod: voicechat mode reloaded 1.2.0 jar.
When u join on server - u got this error (1 screen)
![image](https://user-images.githubusercontent.com/62903401/77957737-5eb5a680-72ed-11ea-865f-1d9262cca88c.png)
VoiceChat working with sometroubles, player1 can hear player2 and player3, but player3 can't hear player1, idk.
While one player live's from server and rejoin - voicechat mod saying that server doesn't support this mod, and can't use voicechat. In log chat - nothing. If u need, i can send u log.

_Sorry for my bad english, if u need, i can explain this on russian._

**Comment by Ivasik78** [comment]
Write me in discord
