### ISSUE TITLE
[1.12] Opening inventory/chest/pause game/etc.. while voice is activated = graphical issue

### ISSUE THREAD

**Issue by Creerio** [Ivasik78/GlibysVoiceChat#11]
> ### Minecraft Informations

Launcher Used : MultiMC V0.6.11 (latest) + Official launcher

Minecraft version : 1.12.2 with Forge 14.23.5.2854 (latest)

Mod version : Latest on [Curseforge](https://www.curseforge.com/minecraft/mc-mods/glibys-voice-chat-reloaded/files/2746796)

> ### Summary of the issue

While having the voice activated, opening any kind of menu (Pause menu, inventory, chest, furnaces and even the mod option) makes the background black.

> ### How to reproduce it

**Step 1**: Take any kind of 1.12.2 minecraft instance, as long as you have the latest forge (14.23.5.2854 as of now) and the mod.

**Step 2**: Go in solo or multiplayer.

**Step 3**: Use the voice button if you are in toggle to speak or maintain the voice button with the push to talk speak mode.

**Step 4**: Open anything. Chest, furnace, crafting table or even the mod options.

> ### Video of the issue

[Here](https://youtu.be/2Gu0xte7nRM).

> ### Suspected cause

I have no idea why this is happening unfortunately.

> ### Additional information

None.

**Comment by Ivasik78** [comment]
Fixed
