### ISSUE TITLE
[1.12.2] Skybox Rendering Issues When GUIs Present

### ISSUE THREAD

**Issue by Zundrel** [Ivasik78/GlibysVoiceChat#3]
When the various GUIs from Gliby's Voice Chat show up on the screen it causes the sun to have a black square around it as well as causing some issues with shaders and such.

I've found the fix for this to simply be switching all GL11 calls to use GlStateManager, which is a very simple, but slightly time consuming, process.

**Comment by Ivasik78** [comment]
Bug fixed in 1.2.0
