### ISSUE TITLE
A question of your mod

### ISSUE THREAD

**Issue by Pro845627** [Ivasik78/GlibysVoiceChat#7]
1. Version Minecraft 1.12.2

2. Version Mod 1.2.0

When the server start and a few minutes later, if me exit the server and re-join, then I can't use the Voice Chat and the menu shows "The server doesn't support voice chat." and i need to restart the server to fix it TEMPORARILY, except you join the server as soon as the server starts and don't exit until the server stops.

**Comment by Ivasik78** [comment]
In February I can check and fix it

**Comment by evanlegamer** [comment]
I have the same problem more or less...
Is there a way to see debug ?

**Comment by Tankonyako** [comment]
same problem

**Comment by evanlegamer** [comment]
still happening

**Comment by Tankonyako** [comment]
waiting for fix, mark this is as critical bug
