### ISSUE TITLE
is this a bug ?

### ISSUE THREAD

**Issue by evanlegamer** [Ivasik78/GlibysVoiceChat#9]
SERVER 1.12.2
FORGE Latest for 1.12.2

LEAK: ByteBuf.release() was not called before it's garbage-collected. Enable advanced leak reporting to find out where the leak occurred. To enable advanced leak reporting, specify the JVM option '-Dio.netty.leakDetection.level=advanced' or call ResourceLeakDetector.setLevel() See http://netty.io/wiki/reference-counted-objects.html for more information.

**Comment by Ivasik78** [comment]
I'll check it later
